language: python
env:
  - TEST_DOCTESTS="true"
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
matrix:
  include:
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
        - IN_PYTHON_33="false"
      virtualenv:
        system_site_packages: true
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - IN_PYTHON_33="false"
      virtualenv:
        system_site_packages: true
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
        - IN_PYTHON_33="true"
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - IN_PYTHON_33="true"
    - python: 2.7
      env: TEST_SPHINX="true"
  allow_failures:
    - python: "pypy"
before_install:
  - if [[ "${TEST_GMPY}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get install libgmp-dev;
      pip install --use-mirrors "gmpy==1.16";
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern;
      pip install --use-mirrors "sphinx==1.1.3";
    fi
  - if [[ "${TEST_MATPLOTLIB}" == "true" && "${IN_PYTHON_33}" == "true"]]; then
      pip install --use-mirrors "matplotlib==1.2.1";
    else
      sudo apt-get install python-matplotlib python3-matplotlib;
    fi
install:
  - python setup.py install
script:
  - bin/test_travis.sh
notifications:
  email: false
