language: python
env:
  - TEST_DOCTESTS="true"
  - TEST_DOCTESTS="false"
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
matrix:
  include:
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
    - python: 2.7
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="false"
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="true"
    - python: 3.3
      env:
        - TEST_GMPY="true"
        - TEST_MATPLOTLIB="true"
        - TEST_DOCTESTS="false"
    - python: 2.7
      env: TEST_SPHINX="true"
  allow_failures:
    - python: "pypy"
before_install:
  - if [[ "${TEST_GMPY}" == "true" ]]; then
      time sudo apt-get update;
      time sudo apt-get install libgmp-dev;
      time pip install "gmpy==1.16";
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      time sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern;
      time pip install "sphinx==1.1.3";
    fi
  - if [[ "${TEST_MATPLOTLIB}" == "true" ]]; then
      time pip install "numpy==1.7.1";
      time pip install "matplotlib==1.2.1";
    fi
install:
  - time python setup.py install
script:
  - time bin/test_travis.sh
notifications:
  email: false
