language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python bin/use2to3; cd py3k-sympy; fi
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of sympy in the source directory.
  - mkdir empty
  - cd empty
  - "echo -e \"import sympy\\nif not sympy.test(): raise Exception('Tests failed')\" | python"
  - "echo -e \"import sympy\\nif not sympy.doctest(): raise Exception('Doctests failed')\" | python"
notifications:
  email: false
