comment: off

codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: null
        branches: null

    patch:
      default:
        target: 0%
        branches: null

  precision: 3
