name: "Check for Broken Links"
on: [push, pull_request]
jobs:

# --------------------------- check for broken Url links ---------------------- #

  check-broken-urls:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python packages
        run: |
        python -m pip install --upgrade pip
        python -m pip install -r doc/requirements.txt
      - name: Scanning for Broken and Redirected Links
        run: cd doc/ && make linkcheck
        continue-on-error: true
      - name: Saving summary of build results
        run: |
          echo "# Broken and Redirected Links" >> $GITHUB_STEP_SUMMARY
          echo "## Broken Links" >> $GITHUB_STEP_SUMMARY
          grep broken doc/_build/linkcheck/output.txt >> $GITHUB_STEP_SUMMARY
          echo "## Links that were 'redirected permanently'" >> $GITHUB_STEP_SUMMARY
          grep 'redirected permanently' doc/_build/linkcheck/output.txt >> $GITHUB_STEP_SUMMARY
          echo "## Links that were 'redirected with Found'" >> $GITHUB_STEP_SUMMARY
          grep 'redirected with Found' doc/_build/linkcheck/output.txt >> $GITHUB_STEP_SUMMARY
      - name: Log Summary URL
        run: |
          GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo "Check log summary here:- $GITHUB_WORKFLOW_URL"
