name: Docs Preview
on: [status]
jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: doc/aptinstall.sh
      - run: sudo apt update
      - run: sudo apt install imagemagick graphviz librsvg2-bin
      - run: pip install -r doc/requirements.txt
      - run: make --directory=doc html
