name: Links (Fail Fast)

on: [push, pull_request]

jobs:
  linkChecker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          fail: false