# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Runs each time a pull request is opened, pushed or merged        #
#                                                                    #
# ------------------------------------------------------------------ #

name: test
on: [push, pull_request]
jobs:

  # -------------------- Code quality ------------------------------ #

  code-quality:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Clone full git history (needed for AUTHORS/mailmap)
          fetch-depth: '0'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath flake8

      - name: Basic code quality tests
        run: bin/test quality

      - name: Run flake8 on the sympy package
        run: flake8 sympy

      - name: Detect invalid escapes like '\e'
        run: python -We:invalid -We::SyntaxWarning -m compileall -f -q sympy/

      - name: Test all modules are listed in setup.py
        run: bin/test_setup.py

      # -- temporarily disabled -- #
      # These checks were too difficult for new contributors. They will
      # need to be made easier to work with before they are reenabled.

      #- name: Test for ambiguous author information in commits
      #  run: bin/mailmap_update.py

      #- name: Make sure all commits have an associated author
      #  run: bin/authors_update.py


  # ----------------------------- mypy ----------------------------- #

  mypy:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Clone full git history (needed for AUTHORS/mailmap)
          fetch-depth: '0'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath mypy

      - name: Run mypy on the sympy package
        run: mypy sympy

  # -------------------- Doctests latest Python -------------------- #

  doctests-latest:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11.0'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/doctest --force-colors
      - run: examples/all.py -q

  # -------------------- Test split 1/2 latest Python -------------- #

  tests1-latest:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=1/2

  # -------------------- Test split 2/2 latest Python -------------- #

  tests2-latest:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=2/2

  # -------------------- Optional dependency tests ----------------- #

  optional-dependencies:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: sudo apt install antlr4 libgfortran5 gfortran libmpfr-dev libmpc-dev
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath gmpy2 matplotlib numpy scipy aesara ipython \
                         symengine cython llvmlite wurlitzer \
                         autowrap numexpr 'antlr4-python3-runtime==4.7.*'
      # Test external imports
      - run: bin/test_external_imports.py
      - run: bin/test_submodule_imports.py
      - run: bin/test_executable.py
      # Test modules with specific dependencies
      - run: bin/test_optional_dependencies.py


  # -------------------- Slow test split 1/2 ----------------------- #

  slow1:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=1/2

  # -------------------- Slow test split 2/2 ----------------------- #

  slow2:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha - 3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=2/2
